### ISSUE TITLE
folder structure

### ISSUE THREAD

**Issue by jaamaalxyz** [shatil24/chatapp3#1]
Hello vai, you did a good job as a learner 👍 💯 . I just want you to notice, you have to organize your folder structure. I know your apps are working well 🚀 . but `components`, `screens` etc, I mean all code folder should be under the `lib` folder according to *flutter documentation*. I hope you cope up and build some more awesome products with *flutter* soon. 

Your co-learner.
Happy Learning :)

**Comment by shatilsarower** [comment]
Sorry to reply but I was busy with my other projects, I just fixed the issue that you noticed, thanks for finding it out, I was a beginner, so that was my limitation. Thanks a lot.
